### ISSUE TITLE
Plugin links to .com (ad page) instead of correct .org site

### ISSUE THREAD

**Issue by mcandre** [y-a-r-g/idea-color-themes#2]

**Comment by y-a-r-g** [comment]
@mcandre Could you please provide more information? I didn't get what is a bug about.

**Comment by mcandre** [comment]
The plugin description for the idea-color-themes plugin in IntelliJ links to a dead website (the .com), that opens tons of popups and ads. The link needs to be corrected to the .org website.

**Comment by y-a-r-g** [comment]
Still cant get it. Could you please provide step-by-step instruction how can I see it?

**Comment by mcandre** [comment]
No problem

1. Launch IntelliJ.
2. Open Settings.
3. Search for "Plugins"
4. Within plugins, search for the "color" plugin.
5. In the info panel, click the homepage links.

**Comment by y-a-r-g** [comment]
Oh, I finally get it!
This is not my plugin. It was updated last time in 2012. There were no ideacolorthemes.org in that year.
Probably some other guys made the similar site but now it's not working anymore and plugin is outdated.

**Comment by mcandre** [comment]
Oh, wow, haha! That's a sanity check I never considered before.
